/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  CacheRules: () => import('#controllers/cache_rules_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  Session: () => import('#controllers/session_controller'),
  Stats: () => import('#controllers/stats_controller'),
}
