/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class CacheRuleSchema extends BaseModel {
  static $columns = ['allowedBodyFields', 'cacheLock', 'createdAt', 'endpointPattern', 'id', 'isActive', 'methods', 'name', 'queryFields', 'rateLimitRps', 'ttlSeconds', 'updatedAt', 'upstreamUrl'] as const
  $columns = CacheRuleSchema.$columns
  @column()
  declare allowedBodyFields: any | null
  @column()
  declare cacheLock: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare endpointPattern: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare methods: any
  @column()
  declare name: string
  @column()
  declare queryFields: any | null
  @column()
  declare rateLimitRps: number | null
  @column()
  declare ttlSeconds: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare upstreamUrl: string
}

export class CacheStatSchema extends BaseModel {
  static $columns = ['cacheHits', 'cacheMisses', 'id', 'ruleId', 'updatedAt'] as const
  $columns = CacheStatSchema.$columns
  @column()
  declare cacheHits: number
  @column()
  declare cacheMisses: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ruleId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
